language: python
sudo: true
python: 3.7
dist: xenial
cache: pip
services:
  - docker

script:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .
  - LC_ALL=C BROWSER=echo make docs mypy lint pytest
